// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// parse_simplex_vertices_cpp
std::vector<arma::uword> parse_simplex_vertices_cpp(const std::string& simplex_str);
RcppExport SEXP _TopTreeSegR_parse_simplex_vertices_cpp(SEXP simplex_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type simplex_str(simplex_strSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_simplex_vertices_cpp(simplex_str));
    return rcpp_result_gen;
END_RCPP
}
// extract_minima_corrected_cpp
arma::uvec extract_minima_corrected_cpp(const List& morse_complex, const arma::mat& vertices, const std::string& temp_dir);
RcppExport SEXP _TopTreeSegR_extract_minima_corrected_cpp(SEXP morse_complexSEXP, SEXP verticesSEXP, SEXP temp_dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type morse_complex(morse_complexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type temp_dir(temp_dirSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_minima_corrected_cpp(morse_complex, vertices, temp_dir));
    return rcpp_result_gen;
END_RCPP
}
// parse_gradient_network_fast
List parse_gradient_network_fast(const std::vector<std::string>& vector_field, const arma::vec& elevations, arma::uword n_vertices);
RcppExport SEXP _TopTreeSegR_parse_gradient_network_fast(SEXP vector_fieldSEXP, SEXP elevationsSEXP, SEXP n_verticesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type vector_field(vector_fieldSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type elevations(elevationsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_vertices(n_verticesSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_gradient_network_fast(vector_field, elevations, n_vertices));
    return rcpp_result_gen;
END_RCPP
}
// compute_ascending_regions
arma::uvec compute_ascending_regions(const List& gradient_network, const arma::uvec& minima, arma::uword n_vertices);
RcppExport SEXP _TopTreeSegR_compute_ascending_regions(SEXP gradient_networkSEXP, SEXP minimaSEXP, SEXP n_verticesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type gradient_network(gradient_networkSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type minima(minimaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_vertices(n_verticesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ascending_regions(gradient_network, minima, n_vertices));
    return rcpp_result_gen;
END_RCPP
}
// build_minima_connectivity_fast
List build_minima_connectivity_fast(const arma::uvec& minima, const arma::mat& vertices, double max_distance);
RcppExport SEXP _TopTreeSegR_build_minima_connectivity_fast(SEXP minimaSEXP, SEXP verticesSEXP, SEXP max_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type minima(minimaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< double >::type max_distance(max_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(build_minima_connectivity_fast(minima, vertices, max_distance));
    return rcpp_result_gen;
END_RCPP
}
// build_minima_connectivity_spatial
List build_minima_connectivity_spatial(const arma::uvec& minima, const arma::mat& vertices, double max_distance, double grid_size);
RcppExport SEXP _TopTreeSegR_build_minima_connectivity_spatial(SEXP minimaSEXP, SEXP verticesSEXP, SEXP max_distanceSEXP, SEXP grid_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type minima(minimaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< double >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< double >::type grid_size(grid_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(build_minima_connectivity_spatial(minima, vertices, max_distance, grid_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TopTreeSegR_parse_simplex_vertices_cpp", (DL_FUNC) &_TopTreeSegR_parse_simplex_vertices_cpp, 1},
    {"_TopTreeSegR_extract_minima_corrected_cpp", (DL_FUNC) &_TopTreeSegR_extract_minima_corrected_cpp, 3},
    {"_TopTreeSegR_parse_gradient_network_fast", (DL_FUNC) &_TopTreeSegR_parse_gradient_network_fast, 3},
    {"_TopTreeSegR_compute_ascending_regions", (DL_FUNC) &_TopTreeSegR_compute_ascending_regions, 3},
    {"_TopTreeSegR_build_minima_connectivity_fast", (DL_FUNC) &_TopTreeSegR_build_minima_connectivity_fast, 3},
    {"_TopTreeSegR_build_minima_connectivity_spatial", (DL_FUNC) &_TopTreeSegR_build_minima_connectivity_spatial, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_TopTreeSegR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
