// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// parse_simplex_vertices_cpp
std::vector<arma::uword> parse_simplex_vertices_cpp(const std::string& simplex_str);
RcppExport SEXP _TopTreeSegR_parse_simplex_vertices_cpp(SEXP simplex_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type simplex_str(simplex_strSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_simplex_vertices_cpp(simplex_str));
    return rcpp_result_gen;
END_RCPP
}
// extract_minima_corrected_cpp
arma::uvec extract_minima_corrected_cpp(const List& morse_complex, const arma::mat& vertices, const std::string& temp_dir);
RcppExport SEXP _TopTreeSegR_extract_minima_corrected_cpp(SEXP morse_complexSEXP, SEXP verticesSEXP, SEXP temp_dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type morse_complex(morse_complexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type temp_dir(temp_dirSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_minima_corrected_cpp(morse_complex, vertices, temp_dir));
    return rcpp_result_gen;
END_RCPP
}
// parse_gradient_network_fast_cpp
List parse_gradient_network_fast_cpp(const std::vector<std::string>& vector_field, const arma::vec& elevations, arma::uword n_vertices);
RcppExport SEXP _TopTreeSegR_parse_gradient_network_fast_cpp(SEXP vector_fieldSEXP, SEXP elevationsSEXP, SEXP n_verticesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type vector_field(vector_fieldSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type elevations(elevationsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_vertices(n_verticesSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_gradient_network_fast_cpp(vector_field, elevations, n_vertices));
    return rcpp_result_gen;
END_RCPP
}
// compute_ascending_regions_fast_cpp
arma::uvec compute_ascending_regions_fast_cpp(const List& gradient_network, const arma::uvec& minima, arma::uword n_vertices);
RcppExport SEXP _TopTreeSegR_compute_ascending_regions_fast_cpp(SEXP gradient_networkSEXP, SEXP minimaSEXP, SEXP n_verticesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type gradient_network(gradient_networkSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type minima(minimaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_vertices(n_verticesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ascending_regions_fast_cpp(gradient_network, minima, n_vertices));
    return rcpp_result_gen;
END_RCPP
}
// build_minima_connectivity_fast_cpp
List build_minima_connectivity_fast_cpp(const arma::uvec& minima, const arma::mat& vertices, double max_distance);
RcppExport SEXP _TopTreeSegR_build_minima_connectivity_fast_cpp(SEXP minimaSEXP, SEXP verticesSEXP, SEXP max_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type minima(minimaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< double >::type max_distance(max_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(build_minima_connectivity_fast_cpp(minima, vertices, max_distance));
    return rcpp_result_gen;
END_RCPP
}
// build_minima_connectivity_spatial_cpp
List build_minima_connectivity_spatial_cpp(const arma::uvec& minima, const arma::mat& vertices, double max_distance, double grid_size);
RcppExport SEXP _TopTreeSegR_build_minima_connectivity_spatial_cpp(SEXP minimaSEXP, SEXP verticesSEXP, SEXP max_distanceSEXP, SEXP grid_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type minima(minimaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< double >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< double >::type grid_size(grid_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(build_minima_connectivity_spatial_cpp(minima, vertices, max_distance, grid_size));
    return rcpp_result_gen;
END_RCPP
}
// build_minima_connectivity_from_saddles_cpp
List build_minima_connectivity_from_saddles_cpp(const std::vector<std::string>& critical_simplices, const std::vector<std::string>& vector_field, const arma::uvec& minima);
RcppExport SEXP _TopTreeSegR_build_minima_connectivity_from_saddles_cpp(SEXP critical_simplicesSEXP, SEXP vector_fieldSEXP, SEXP minimaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type critical_simplices(critical_simplicesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type vector_field(vector_fieldSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type minima(minimaSEXP);
    rcpp_result_gen = Rcpp::wrap(build_minima_connectivity_from_saddles_cpp(critical_simplices, vector_field, minima));
    return rcpp_result_gen;
END_RCPP
}
// propagate_labels_minima_graph_cpp
arma::uvec propagate_labels_minima_graph_cpp(const List& minima_graph, const arma::uvec& seed_indices, const arma::uvec& seed_labels, const arma::vec& elevations, arma::uword n_minima);
RcppExport SEXP _TopTreeSegR_propagate_labels_minima_graph_cpp(SEXP minima_graphSEXP, SEXP seed_indicesSEXP, SEXP seed_labelsSEXP, SEXP elevationsSEXP, SEXP n_minimaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type minima_graph(minima_graphSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type seed_indices(seed_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type seed_labels(seed_labelsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type elevations(elevationsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_minima(n_minimaSEXP);
    rcpp_result_gen = Rcpp::wrap(propagate_labels_minima_graph_cpp(minima_graph, seed_indices, seed_labels, elevations, n_minima));
    return rcpp_result_gen;
END_RCPP
}
// build_minima_connectivity_optimized_vpath_cpp
List build_minima_connectivity_optimized_vpath_cpp(const std::vector<std::string>& critical_simplices, const std::vector<std::string>& vector_field, const arma::uvec& minima);
RcppExport SEXP _TopTreeSegR_build_minima_connectivity_optimized_vpath_cpp(SEXP critical_simplicesSEXP, SEXP vector_fieldSEXP, SEXP minimaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type critical_simplices(critical_simplicesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type vector_field(vector_fieldSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type minima(minimaSEXP);
    rcpp_result_gen = Rcpp::wrap(build_minima_connectivity_optimized_vpath_cpp(critical_simplices, vector_field, minima));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TopTreeSegR_parse_simplex_vertices_cpp", (DL_FUNC) &_TopTreeSegR_parse_simplex_vertices_cpp, 1},
    {"_TopTreeSegR_extract_minima_corrected_cpp", (DL_FUNC) &_TopTreeSegR_extract_minima_corrected_cpp, 3},
    {"_TopTreeSegR_parse_gradient_network_fast_cpp", (DL_FUNC) &_TopTreeSegR_parse_gradient_network_fast_cpp, 3},
    {"_TopTreeSegR_compute_ascending_regions_fast_cpp", (DL_FUNC) &_TopTreeSegR_compute_ascending_regions_fast_cpp, 3},
    {"_TopTreeSegR_build_minima_connectivity_fast_cpp", (DL_FUNC) &_TopTreeSegR_build_minima_connectivity_fast_cpp, 3},
    {"_TopTreeSegR_build_minima_connectivity_spatial_cpp", (DL_FUNC) &_TopTreeSegR_build_minima_connectivity_spatial_cpp, 4},
    {"_TopTreeSegR_build_minima_connectivity_from_saddles_cpp", (DL_FUNC) &_TopTreeSegR_build_minima_connectivity_from_saddles_cpp, 3},
    {"_TopTreeSegR_propagate_labels_minima_graph_cpp", (DL_FUNC) &_TopTreeSegR_propagate_labels_minima_graph_cpp, 5},
    {"_TopTreeSegR_build_minima_connectivity_optimized_vpath_cpp", (DL_FUNC) &_TopTreeSegR_build_minima_connectivity_optimized_vpath_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_TopTreeSegR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
