# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_simplex_vertices_cpp <- function(simplex_str) {
    .Call(`_TopTreeSegR_parse_simplex_vertices_cpp`, simplex_str)
}

extract_minima_corrected_cpp <- function(morse_complex, vertices, temp_dir = "") {
    .Call(`_TopTreeSegR_extract_minima_corrected_cpp`, morse_complex, vertices, temp_dir)
}

parse_gradient_network_fast <- function(vector_field, n_vertices) {
    .Call(`_TopTreeSegR_parse_gradient_network_fast`, vector_field, n_vertices)
}

compute_ascending_regions_fast <- function(gradient_network, minima, n_vertices) {
    .Call(`_TopTreeSegR_compute_ascending_regions_fast`, gradient_network, minima, n_vertices)
}

build_minima_connectivity_fast <- function(minima, vertices, max_distance = 2.0) {
    .Call(`_TopTreeSegR_build_minima_connectivity_fast`, minima, vertices, max_distance)
}

build_minima_connectivity_spatial <- function(minima, vertices, max_distance = 2.0, grid_size = 5.0) {
    .Call(`_TopTreeSegR_build_minima_connectivity_spatial`, minima, vertices, max_distance, grid_size)
}

