# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

map_mesh_to_points_cpp <- function(mesh_coords, mesh_labels, point_coords, max_distance = 2.0) {
    .Call(`_TopTreeSegR_map_mesh_to_points_cpp`, mesh_coords, mesh_labels, point_coords, max_distance)
}

tree_segment_cpp <- function(vertices_df, morse_complex_data, stem_height = 0.5, spatial_eps = 1.0, max_distance = 2.0, grid_size = 5.0) {
    .Call(`_TopTreeSegR_tree_segment_cpp`, vertices_df, morse_complex_data, stem_height, spatial_eps, max_distance, grid_size)
}

morse_smale_segment_cpp <- function(vertices_df, morse_complex_data, stem_height = 0.5, spatial_eps = 1.0) {
    .Call(`_TopTreeSegR_morse_smale_segment_cpp`, vertices_df, morse_complex_data, stem_height, spatial_eps)
}

get_mesh_coords_cpp <- function(vertices_df) {
    .Call(`_TopTreeSegR_get_mesh_coords_cpp`, vertices_df)
}

MRFBR_cpp <- function(coords, labels, spatial_sigma = 1.0, intensity = 1.0, iterations = 2L) {
    .Call(`_TopTreeSegR_MRFBR_cpp`, coords, labels, spatial_sigma, intensity, iterations)
}

BBR_ultrafast_cpp <- function(coords, labels, prior_strength = 1.0, likelihood_strength = 2.0, confidence_threshold = 1.3, cores = 4L) {
    .Call(`_TopTreeSegR_BBR_ultrafast_cpp`, coords, labels, prior_strength, likelihood_strength, confidence_threshold, cores)
}

