# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_simplex_vertices_cpp <- function(simplex_str) {
    .Call(`_TopTreeSegR_parse_simplex_vertices_cpp`, simplex_str)
}

extract_minima_corrected_cpp <- function(morse_complex, vertices, temp_dir = "") {
    .Call(`_TopTreeSegR_extract_minima_corrected_cpp`, morse_complex, vertices, temp_dir)
}

parse_gradient_network_fast_cpp <- function(vector_field, elevations, n_vertices) {
    .Call(`_TopTreeSegR_parse_gradient_network_fast_cpp`, vector_field, elevations, n_vertices)
}

compute_ascending_regions_fast_cpp <- function(gradient_network, minima, n_vertices) {
    .Call(`_TopTreeSegR_compute_ascending_regions_fast_cpp`, gradient_network, minima, n_vertices)
}

build_minima_connectivity_fast_cpp <- function(minima, vertices, max_distance = 2.0) {
    .Call(`_TopTreeSegR_build_minima_connectivity_fast_cpp`, minima, vertices, max_distance)
}

build_minima_connectivity_spatial_cpp <- function(minima, vertices, max_distance = 2.0, grid_size = 5.0) {
    .Call(`_TopTreeSegR_build_minima_connectivity_spatial_cpp`, minima, vertices, max_distance, grid_size)
}

build_minima_connectivity_from_saddles_cpp <- function(critical_simplices, vector_field, minima) {
    .Call(`_TopTreeSegR_build_minima_connectivity_from_saddles_cpp`, critical_simplices, vector_field, minima)
}

propagate_labels_minima_graph_cpp <- function(minima_graph, seed_indices, seed_labels, elevations, n_minima) {
    .Call(`_TopTreeSegR_propagate_labels_minima_graph_cpp`, minima_graph, seed_indices, seed_labels, elevations, n_minima)
}

build_minima_connectivity_optimized_vpath_cpp <- function(critical_simplices, vector_field, minima, max_vpath_length = 100L) {
    .Call(`_TopTreeSegR_build_minima_connectivity_optimized_vpath_cpp`, critical_simplices, vector_field, minima, max_vpath_length)
}

